version: '3.8'
services:
  app:
    image: spring-boot-docker-secrets:latest
    ports:
      - 4000:8080
    secrets:
      - source: important-secret
        target: super-important-secret

secrets:
  important-secret:
    external: true


